# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142LjwzOd8amWaSny_nNrQI0hKTkofNdk
"""

from google.colab import drive
drive.mount("/content/gdrive")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/gdrive/MyDrive/datasets/CAR DETAILS FROM CAR DEKHO.csv")

df.head(3)

sns.barplot(x="fuel",y="selling_price",data=df)

sns.barplot(x="fuel",y="selling_price",data=df,hue="owner")

sns.barplot(y="year",x="selling_price",data=df,ci=None,orient="h",color="cyan")

display(df)

df.head().style.set_table_styles([{'selector' : 'tr:hover','props' : [('border','2px solid green')]}])

df.style.set_table_styles()