# -*- coding: utf-8 -*-
"""Prices2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19cuPJXQD3uukGKNHV73yD0exy5ArczOg
"""

import numpy as np
import pandas as pd

df = pd.read_excel("Prices2.xlsx")

df.head()

da = df.Date.unique()

new_dic={}
flag=True
for i in da:
  df1 = df[df.Date==i]
  a=[i.month for i in df1["Contract Month"]]
  b=[i.year for i in df1["Contract Month"]]
  c=len(a)
  hh=[]
  for w in range(0,c):
    g=(a[w],b[w])
    hh.append(g)
  df1["Month"]=hh
  if flag:
    dfn=pd.DataFrame({"Month":hh})
    flag = False
  df2=pd.DataFrame({"Month":hh})
  if dfn.iloc[1,0]==df2.iloc[1,0]:
    df2=pd.merge(dfn,df2,how="outer")
  else:
    df2=pd.merge(dfn,df2,how="inner")
  a=pd.merge(df2,df1.loc[:,["Month","Price"]],how="outer",on="Month")
  new_dic[i]=a.Price

final_df = pd.DataFrame.from_dict(new_dic,orient="index")

final_df.fillna(method="ffill",axis=0,inplace=True)

final_df.columns=["Month "+str(int(i)+1) for i in final_df.columns]

final_df

final_df.to_excel("Final.xlsx")